# golangci-lint configuration for USFM Parser
version: 2

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - build

linters:
  enable:
    # Default enabled linters (always on)
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Additional quality linters
    - bodyclose
    - cyclop
    - dupl
    - errorlint
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - nakedret
    - prealloc
    - revive
    - unconvert
    - unparam

linters-settings:
  gocyclo:
    min-complexity: 15
  
  cyclop:
    max-complexity: 15
  
  gocognit:
    min-complexity: 20
    
  misspell:
    locale: US
    ignore-words:
      - usfm
      - USFM
      - BSB
      - SFM
      - Berean
  
  gosec:
    confidence: medium

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocognit
        - gocyclo
        - dupl