# GoReleaser configuration for USFM Parser
version: 2

# Environment variables for build
env:
  - GO111MODULE=on
  - CGO_ENABLED=0

# Build configuration
builds:
  - id: usfmp
    main: ./cmd/usfmp
    binary: usfmp
    
    # Build for multiple platforms
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    
    goarch:
      - amd64
      - arm64
      - arm
    
    goarm:
      - "6"
      - "7"
    
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
    
    # Build flags and ldflags
    flags:
      - -trimpath
    
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

# Archive configuration
archives:
  - id: usfmp-archive
    name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm" }}arm{{ .Arm }}
      {{- else }}{{ .Arch }}{{ end }}
    
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

# Checksums
checksum:
  name_template: 'checksums.txt'

# Snapshot configuration for development builds
snapshot:
  version_template: "{{ incpatch .Version }}-next"

# Changelog configuration
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^style:'
  groups:
    - title: 'Features'
      regexp: '^.*?(feat|feature)(\(.+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1
    - title: 'Performance improvements'
      regexp: '^.*?perf(\(.+\))??!?:.+$'
      order: 2
    - title: 'Dependency updates'
      regexp: '^.*?(deps|dep)(\(.+\))??!?:.+$'
      order: 3
    - title: 'Other changes'
      order: 999

# GitHub release configuration
release:
  draft: false
  prerelease: auto
  make_latest: true
  mode: replace
  header: |
    ## USFM Parser {{.Tag}}
    
    A command-line tool and Go library for parsing USFM (Unified Standard Format Marker) biblical texts.
    
    ### Installation
    
    Download the appropriate binary for your system from the assets below, or install using Go:
    
    ```bash
    go install github.com/arenzana/usfmp/cmd/usfmp@{{.Tag}}
    ```
    
  footer: |
    
    ### Checksums
    
    All binaries are signed and checksums are provided for verification.
    
    **Full Changelog**: https://github.com/arenzana/usfmp/compare/{{.PreviousTag}}...{{.Tag}}
    
  name_template: "{{.ProjectName}} {{.Version}}"
  
  # Extra files to include in release
  extra_files:
    - glob: ./bsb_usfm/*.SFM
    - glob: ./bsb_usfm/*.xml
    - glob: ./bsb_usfm/*.sty
    - glob: ./bsb_usfm/*.vrs
    - glob: ./bsb_usfm/*.ldml